name: Multi-Platform Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Show Operating System
        run: echo "Running on ${{ matrix.os }}"
